package tyoSuunnittelija.test;
// Generated by ComTest BEGIN
import java.io.File;
import tyoSuunnittelija.*;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2025.04.23 13:28:26 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class PellotTest {



  // Generated by ComTest BEGIN
  /** 
   * testPoista92 
   * @throws SailoException when error
   */
  @Test
  public void testPoista92() throws SailoException {    // Pellot: 92
    Pellot testiPellot = new Pellot(); 
    Pelto testiPelto21 = new Pelto(); testiPelto21.kokeilePelto(2); 
    Pelto testiPelto11 = new Pelto(); testiPelto11.kokeilePelto(1); 
    Pelto testiPelto22 = new Pelto(); testiPelto22.kokeilePelto(2); 
    Pelto testiPelto12 = new Pelto(); testiPelto12.kokeilePelto(1); 
    Pelto testiPelto23 = new Pelto(); testiPelto23.kokeilePelto(2); 
    testiPellot.lisaa(testiPelto21); 
    testiPellot.lisaa(testiPelto11); 
    testiPellot.lisaa(testiPelto22); 
    testiPellot.lisaa(testiPelto12); 
    assertEquals("From: Pellot line: 105", false, testiPellot.poista(testiPelto23)); assertEquals("From: Pellot line: 105", 4, testiPellot.getLkm()); 
    assertEquals("From: Pellot line: 106", true, testiPellot.poista(testiPelto11)); assertEquals("From: Pellot line: 106", 3, testiPellot.getLkm()); 
    List<Pelto> h = testiPellot.annaPellot(1); 
    assertEquals("From: Pellot line: 108", 1, h.size()); 
    assertEquals("From: Pellot line: 109", testiPelto12, h.get(0)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testPoistaTallennuksenPellot125 */
  @Test
  public void testPoistaTallennuksenPellot125() {    // Pellot: 125
    Pellot testiPellot = new Pellot(); 
    Pelto testiPelto21 = new Pelto(); testiPelto21.kokeilePelto(2); 
    Pelto testiPelto11 = new Pelto(); testiPelto11.kokeilePelto(1); 
    Pelto testiPelto22 = new Pelto(); testiPelto22.kokeilePelto(2); 
    Pelto testiPelto12 = new Pelto(); testiPelto12.kokeilePelto(1); 
    Pelto testiPelto23 = new Pelto(); testiPelto23.kokeilePelto(2); 
    testiPellot.lisaa(testiPelto21); 
    testiPellot.lisaa(testiPelto11); 
    testiPellot.lisaa(testiPelto22); 
    testiPellot.lisaa(testiPelto12); 
    testiPellot.lisaa(testiPelto23); 
    assertEquals("From: Pellot line: 137", 3, testiPellot.poistaTallennuksenPellot(2)); assertEquals("From: Pellot line: 137", 2, testiPellot.getLkm()); 
    assertEquals("From: Pellot line: 138", 0, testiPellot.poistaTallennuksenPellot(3)); assertEquals("From: Pellot line: 138", 2, testiPellot.getLkm()); 
    List<Pelto> h = testiPellot.annaPellot(2); 
    assertEquals("From: Pellot line: 140", 0, h.size()); 
    h = testiPellot.annaPellot(1); 
    assertEquals("From: Pellot line: 142", testiPelto11, h.get(0)); 
    assertEquals("From: Pellot line: 143", testiPelto12, h.get(1)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta169 
   * @throws SailoException when error
   */
  @Test
  public void testLueTiedostosta169() throws SailoException {    // Pellot: 169
    Pellot pellot = new Pellot(); 
    Pelto testiPelto21 = new Pelto(); testiPelto21.kokeilePelto(2); 
    Pelto testiPelto11 = new Pelto(); testiPelto11.kokeilePelto(1); 
    Pelto testiPelto22 = new Pelto(); testiPelto22.kokeilePelto(2); 
    Pelto testiPelto12 = new Pelto(); testiPelto12.kokeilePelto(1); 
    Pelto testiPelto23 = new Pelto(); testiPelto23.kokeilePelto(2); 
    String tiedNimi = "data\\testidata\\testiPellot"; 
    File ftied = new File(tiedNimi+".dat"); 
    try {
    pellot.lueTiedostosta(ftied.getName()); 
    fail("Pellot: 181 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    pellot.lisaa(testiPelto21); 
    pellot.lisaa(testiPelto11); 
    pellot.lisaa(testiPelto22); 
    pellot.lisaa(testiPelto12); 
    pellot.lisaa(testiPelto23); 
    pellot.talleta(); 
    pellot.lueTiedostosta(tiedNimi+".dat"); 
    Iterator<Pelto> i = pellot.iterator(); 
    assertEquals("From: Pellot line: 191", testiPelto21.toString(), i.next().toString()); 
    assertEquals("From: Pellot line: 192", testiPelto11.toString(), i.next().toString()); 
    assertEquals("From: Pellot line: 193", testiPelto22.toString(), i.next().toString()); 
    assertEquals("From: Pellot line: 194", testiPelto12.toString(), i.next().toString()); 
    assertEquals("From: Pellot line: 195", testiPelto23.toString(), i.next().toString()); 
    assertEquals("From: Pellot line: 196", false, i.hasNext()); 
    pellot.lisaa(testiPelto23); 
    pellot.talleta(); 
    assertEquals("From: Pellot line: 199", true, ftied.delete()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testIterator299 */
  @Test
  public void testIterator299() {    // Pellot: 299
    Pellot testiPellot2 = new Pellot(); 
    Pelto testiPelto21 = new Pelto(2); testiPellot2.lisaa(testiPelto21); 
    Pelto testiPelto11 = new Pelto(1); testiPellot2.lisaa(testiPelto11); 
    Pelto testiPelto22 = new Pelto(2); testiPellot2.lisaa(testiPelto22); 
    Pelto testiPelto12 = new Pelto(1); testiPellot2.lisaa(testiPelto12); 
    Pelto testiPelto23 = new Pelto(2); testiPellot2.lisaa(testiPelto23); 
    Iterator<Pelto> i2=testiPellot2.iterator(); 
    assertEquals("From: Pellot line: 311", testiPelto21, i2.next()); 
    assertEquals("From: Pellot line: 312", testiPelto11, i2.next()); 
    assertEquals("From: Pellot line: 313", testiPelto22, i2.next()); 
    assertEquals("From: Pellot line: 314", testiPelto12, i2.next()); 
    assertEquals("From: Pellot line: 315", testiPelto23, i2.next()); 
    try {
    assertEquals("From: Pellot line: 316", testiPelto12, i2.next()); 
    fail("Pellot: 316 Did not throw NoSuchElementException");
    } catch(NoSuchElementException _e_){ _e_.getMessage(); }
    int n = 0; 
    int tnrot[] = { 2,1,2,1,2} ; 
    for ( Pelto pel : testiPellot2) {
    assertEquals("From: Pellot line: 322", tnrot[n], pel.getTallennusNro()); n++; 
    }
    assertEquals("From: Pellot line: 325", 5, n); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaPellot341 */
  @Test
  public void testAnnaPellot341() {    // Pellot: 341
    Pellot testiPellot2 = new Pellot(); 
    Pelto testiPelto21 = new Pelto(2); testiPellot2.lisaa(testiPelto21); 
    Pelto testiPelto11 = new Pelto(1); testiPellot2.lisaa(testiPelto11); 
    Pelto testiPelto22 = new Pelto(2); testiPellot2.lisaa(testiPelto22); 
    Pelto testiPelto12 = new Pelto(1); testiPellot2.lisaa(testiPelto12); 
    Pelto testiPelto23 = new Pelto(2); testiPellot2.lisaa(testiPelto23); 
    Pelto testiPelto51 = new Pelto(5); testiPellot2.lisaa(testiPelto51); 
    List<Pelto> loytyneet; 
    loytyneet = testiPellot2.annaPellot(3); 
    assertEquals("From: Pellot line: 354", 0, loytyneet.size()); 
    loytyneet = testiPellot2.annaPellot(1); 
    assertEquals("From: Pellot line: 356", 2, loytyneet.size()); 
    assertEquals("From: Pellot line: 357", true, loytyneet.get(0) == testiPelto11); 
    assertEquals("From: Pellot line: 358", true, loytyneet.get(1) == testiPelto12); 
    loytyneet = testiPellot2.annaPellot(5); 
    assertEquals("From: Pellot line: 360", 1, loytyneet.size()); 
    assertEquals("From: Pellot line: 361", true, loytyneet.get(0) == testiPelto51); 
  } // Generated by ComTest END
}