package tyoSuunnittelija.test;
// Generated by ComTest BEGIN
import tyoSuunnittelija.*;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2025.03.17 18:25:22 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class PellotTest {



  // Generated by ComTest BEGIN
  /** testIterator71 */
  @Test
  public void testIterator71() {    // Pellot: 71
    Pellot testiPellot2 = new Pellot(); 
    Pelto testiPelto21 = new Pelto(2); testiPellot2.lisaa(testiPelto21); 
    Pelto testiPelto11 = new Pelto(1); testiPellot2.lisaa(testiPelto11); 
    Pelto testiPelto22 = new Pelto(2); testiPellot2.lisaa(testiPelto22); 
    Pelto testiPelto12 = new Pelto(1); testiPellot2.lisaa(testiPelto12); 
    Pelto testiPelto23 = new Pelto(2); testiPellot2.lisaa(testiPelto23); 
    Iterator<Pelto> i2=testiPellot2.iterator(); 
    assertEquals("From: Pellot line: 83", testiPelto21, i2.next()); 
    assertEquals("From: Pellot line: 84", testiPelto11, i2.next()); 
    assertEquals("From: Pellot line: 85", testiPelto22, i2.next()); 
    assertEquals("From: Pellot line: 86", testiPelto12, i2.next()); 
    assertEquals("From: Pellot line: 87", testiPelto23, i2.next()); 
    try {
    assertEquals("From: Pellot line: 88", testiPelto12, i2.next()); 
    fail("Pellot: 88 Did not throw NoSuchElementException");
    } catch(NoSuchElementException _e_){ _e_.getMessage(); }
    int n = 0; 
    int tnrot[] = { 2,1,2,1,2} ; 
    for ( Pelto pel : testiPellot2) {
    assertEquals("From: Pellot line: 94", tnrot[n], pel.getTallennusNro()); n++; 
    }
    assertEquals("From: Pellot line: 97", 5, n); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaPellot113 */
  @Test
  public void testAnnaPellot113() {    // Pellot: 113
    Pellot testiPellot2 = new Pellot(); 
    Pelto testiPelto21 = new Pelto(2); testiPellot2.lisaa(testiPelto21); 
    Pelto testiPelto11 = new Pelto(1); testiPellot2.lisaa(testiPelto11); 
    Pelto testiPelto22 = new Pelto(2); testiPellot2.lisaa(testiPelto22); 
    Pelto testiPelto12 = new Pelto(1); testiPellot2.lisaa(testiPelto12); 
    Pelto testiPelto23 = new Pelto(2); testiPellot2.lisaa(testiPelto23); 
    Pelto testiPelto51 = new Pelto(5); testiPellot2.lisaa(testiPelto51); 
    List<Pelto> loytyneet; 
    loytyneet = testiPellot2.annaPellot(3); 
    assertEquals("From: Pellot line: 126", 0, loytyneet.size()); 
    loytyneet = testiPellot2.annaPellot(1); 
    assertEquals("From: Pellot line: 128", 2, loytyneet.size()); 
    assertEquals("From: Pellot line: 129", true, loytyneet.get(0) == testiPelto11); 
    assertEquals("From: Pellot line: 130", true, loytyneet.get(1) == testiPelto12); 
    loytyneet = testiPellot2.annaPellot(5); 
    assertEquals("From: Pellot line: 132", 1, loytyneet.size()); 
    assertEquals("From: Pellot line: 133", true, loytyneet.get(0) == testiPelto51); 
  } // Generated by ComTest END
}