package tyoSuunnittelija.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import tyoSuunnittelija.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2025.04.21 21:10:37 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class PeltoTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi170 */
  @Test
  public void testRekisteroi170() {    // Pelto: 170
    Pelto testiPelto2 = new Pelto(); 
    assertEquals("From: Pelto line: 172", 0, testiPelto2.getTunnusNro()); 
    testiPelto2.rekisteroi(); 
    Pelto testiPelto3 = new Pelto(); 
    testiPelto3.rekisteroi(); 
    int n1 = testiPelto2.getTunnusNro(); 
    int n2 = testiPelto3.getTunnusNro(); 
    assertEquals("From: Pelto line: 178", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString219 */
  @Test
  public void testToString219() {    // Pelto: 219
    Pelto pelto = new Pelto(); 
    pelto.parse("   2   |  10  |   Pelto 20  | Äestys | false | Maissi | false | Kerran | false | Poisto | false | Puinti | false |"); 
    assertEquals("From: Pelto line: 222", "2|10|Pelto 20|Äestys|false|Maissi|false|Kerran|false|Poisto|false|Puinti|false", pelto.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse237 */
  @Test
  public void testParse237() {    // Pelto: 237
    Pelto pelto = new Pelto(); 
    pelto.parse("   2   |  10  |   Pelto 20  | Äestys | false | Maissi | false | Kerran | false | Poisto | false | Puinti | false |"); 
    assertEquals("From: Pelto line: 240", 10, pelto.getTallennusNro()); 
    assertEquals("From: Pelto line: 241", "2|10|Pelto 20|Äestys|false|Maissi|false|Kerran|false|Poisto|false|Puinti|false", pelto.toString()); 
    pelto.rekisteroi(); 
    int n = pelto.getTunnusNro(); 
    pelto.parse(""+(n+20)); 
    pelto.rekisteroi(); 
    assertEquals("From: Pelto line: 246", n+20+1, pelto.getTunnusNro()); 
    assertEquals("From: Pelto line: 247", "" + (n+20+1) + "|10|Pelto 20|Äestys|false|Maissi|false|Kerran|false|Poisto|false|Puinti|false", pelto.toString()); 
  } // Generated by ComTest END
}