package tyoSuunnittelija.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import tyoSuunnittelija.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2025.04.23 13:28:33 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class PeltoTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi297 */
  @Test
  public void testRekisteroi297() {    // Pelto: 297
    Pelto testiPelto2 = new Pelto(); 
    assertEquals("From: Pelto line: 299", 0, testiPelto2.getTunnusNro()); 
    testiPelto2.rekisteroi(); 
    Pelto testiPelto3 = new Pelto(); 
    testiPelto3.rekisteroi(); 
    int n1 = testiPelto2.getTunnusNro(); 
    int n2 = testiPelto3.getTunnusNro(); 
    assertEquals("From: Pelto line: 305", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString346 */
  @Test
  public void testToString346() {    // Pelto: 346
    Pelto pelto = new Pelto(); 
    pelto.parse("   2   |  10  |   Pelto 20  | Äestys | false | Maissi | false | Kerran | false | Poisto | false | Puinti | false |"); 
    assertEquals("From: Pelto line: 349", "2|10|Pelto 20|Äestys|false|Maissi|false|Kerran|false|Poisto|false|Puinti|false", pelto.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse364 */
  @Test
  public void testParse364() {    // Pelto: 364
    Pelto pelto = new Pelto(); 
    pelto.parse("   2   |  10  |   Pelto 20  | Äestys | false | Maissi | false | Kerran | false | Poisto | false | Puinti | false |"); 
    assertEquals("From: Pelto line: 367", 10, pelto.getTallennusNro()); 
    assertEquals("From: Pelto line: 368", "2|10|Pelto 20|Äestys|false|Maissi|false|Kerran|false|Poisto|false|Puinti|false", pelto.toString()); 
    pelto.rekisteroi(); 
    int n = pelto.getTunnusNro(); 
    pelto.parse(""+(n+20)); 
    pelto.rekisteroi(); 
    assertEquals("From: Pelto line: 373", n+20+1, pelto.getTunnusNro()); 
    assertEquals("From: Pelto line: 374", "" + (n+20+1) + "|10|Pelto 20|Äestys|false|Maissi|false|Kerran|false|Poisto|false|Puinti|false", pelto.toString()); 
  } // Generated by ComTest END
}