package tyoSuunnittelija.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import tyoSuunnittelija.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2025.03.17 17:25:04 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class PeltoTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi93 */
  @Test
  public void testRekisteroi93() {    // Pelto: 93
    Pelto testiPelto2 = new Pelto(); 
    assertEquals("From: Pelto line: 95", 0, testiPelto2.getTunnusNro()); 
    testiPelto2.rekisteroi(); 
    Pelto testiPelto3 = new Pelto(); 
    testiPelto3.rekisteroi(); 
    int n1 = testiPelto2.getTunnusNro(); 
    int n2 = testiPelto3.getTunnusNro(); 
    assertEquals("From: Pelto line: 101", n2-1, n1); 
  } // Generated by ComTest END
}