package tyoSuunnittelija.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import tyoSuunnittelija.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2025.04.07 18:44:52 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class TallennusTest {



  // Generated by ComTest BEGIN
  /** testGetNimi25 */
  @Test
  public void testGetNimi25() {    // Tallennus: 25
    Tallennus testiTallennus2 = new Tallennus(); 
    testiTallennus2.kokeileTallennus(); 
    { String _l_=testiTallennus2.getNimi(),_r_="Tallennus .*"; if ( !_l_.matches(_r_) ) fail("From: Tallennus line: 28" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}; 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi69 */
  @Test
  public void testRekisteroi69() {    // Tallennus: 69
    Tallennus testiTallennus3 = new Tallennus(); 
    assertEquals("From: Tallennus line: 71", 0, testiTallennus3.getTunnusNro()); 
    testiTallennus3.rekisteroi(); 
    Tallennus testiTallennus4 = new Tallennus(); 
    testiTallennus4.rekisteroi(); 
    int n1 = testiTallennus3.getTunnusNro(); 
    int n2 = testiTallennus4.getTunnusNro(); 
    assertEquals("From: Tallennus line: 77", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString111 */
  @Test
  public void testToString111() {    // Tallennus: 111
    Tallennus tallennus= new Tallennus(); 
    tallennus.parse(" 1 | Tallennus 1"); 
    assertEquals("From: Tallennus line: 114", "1|Tallennus 1", tallennus.toString());
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse129 */
  @Test
  public void testParse129() {    // Tallennus: 129
    Tallennus tallennus = new Tallennus(); 
    tallennus.parse("   3  |  Tallennus 3"); 
    assertEquals("From: Tallennus line: 132", 3, tallennus.getTunnusNro()); 
    assertEquals("From: Tallennus line: 133", "3|Tallennus 3", tallennus.toString());
    tallennus.rekisteroi(); 
    int n = tallennus.getTunnusNro(); 
    tallennus.parse(""+(n+20)); 
    tallennus.rekisteroi(); 
    assertEquals("From: Tallennus line: 139", n+20+1, tallennus.getTunnusNro()); 
  } // Generated by ComTest END
}