package tyoSuunnittelija.test;
// Generated by ComTest BEGIN
import java.io.File;
import java.util.Iterator;
import static org.junit.Assert.*;
import org.junit.*;
import tyoSuunnittelija.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2025.04.08 11:11:27 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class TallennuksetTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa38 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa38() throws SailoException {    // Tallennukset: 38
    Tallennukset tallennukset = new Tallennukset(); 
    Tallennus testiTallennus3 = new Tallennus(), testiTallennus4 = new Tallennus(); 
    assertEquals("From: Tallennukset line: 42", 0, tallennukset.getLkm()); 
    tallennukset.lisaa(testiTallennus3); assertEquals("From: Tallennukset line: 43", 1, tallennukset.getLkm()); 
    tallennukset.lisaa(testiTallennus4); assertEquals("From: Tallennukset line: 44", 2, tallennukset.getLkm()); 
    tallennukset.lisaa(testiTallennus3); assertEquals("From: Tallennukset line: 45", 3, tallennukset.getLkm()); 
    assertEquals("From: Tallennukset line: 46", testiTallennus3, tallennukset.anna(0)); 
    assertEquals("From: Tallennukset line: 47", testiTallennus4, tallennukset.anna(1)); 
    assertEquals("From: Tallennukset line: 48", testiTallennus3, tallennukset.anna(2)); 
    assertEquals("From: Tallennukset line: 49", false, tallennukset.anna(1) == testiTallennus3); 
    assertEquals("From: Tallennukset line: 50", true, tallennukset.anna(1) == testiTallennus4); 
    try {
    assertEquals("From: Tallennukset line: 51", testiTallennus3, tallennukset.anna(3)); 
    fail("Tallennukset: 51 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    tallennukset.lisaa(testiTallennus3); assertEquals("From: Tallennukset line: 52", 4, tallennukset.getLkm()); 
    tallennukset.lisaa(testiTallennus3); assertEquals("From: Tallennukset line: 53", 5, tallennukset.getLkm()); 
    tallennukset.lisaa(testiTallennus3); assertEquals("From: Tallennukset line: 54", 6, tallennukset.getLkm()); 
    tallennukset.lisaa(testiTallennus3); assertEquals("From: Tallennukset line: 55", 7, tallennukset.getLkm()); 
    tallennukset.lisaa(testiTallennus3); assertEquals("From: Tallennukset line: 56", 8, tallennukset.getLkm()); 
    tallennukset.lisaa(testiTallennus3); assertEquals("From: Tallennukset line: 57", 9, tallennukset.getLkm()); 
    tallennukset.lisaa(testiTallennus3); assertEquals("From: Tallennukset line: 58", 10, tallennukset.getLkm()); 
    try {
    tallennukset.lisaa(testiTallennus3); 
    fail("Tallennukset: 59 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta89 
   * @throws SailoException when error
   */
  @Test
  public void testLueTiedostosta89() throws SailoException {    // Tallennukset: 89
    Tallennukset tallennukset = new Tallennukset(); 
    Tallennus tallennus1 = new Tallennus(), tallennus2 = new Tallennus(); 
    tallennus1.kokeileTallennus(); 
    tallennus2.kokeileTallennus(); 
    String tiedNimi = "data\\testidata\\testiTallennukset"; 
    File ftied = new File(tiedNimi+".dat"); 
    try {
    tallennukset.lueTiedostosta(ftied.getName()); 
    fail("Tallennukset: 101 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    tallennukset.lisaa(tallennus1); 
    tallennukset.lisaa(tallennus2); 
    tallennukset.talleta(); 
    tallennukset = new Tallennukset(); 
    tallennukset.lueTiedostosta(tiedNimi+".dat"); 
    Iterator<Tallennus> i = tallennukset.iterator(); 
    assertEquals("From: Tallennukset line: 108", tallennus1, i.next()); 
    assertEquals("From: Tallennukset line: 109", tallennus2, i.next()); 
    assertEquals("From: Tallennukset line: 110", false, i.hasNext()); 
    tallennukset.lisaa(tallennus2); 
    tallennukset.talleta(); 
    assertEquals("From: Tallennukset line: 113", true, ftied.delete()); 
    File fbak = new File(tiedNimi+".bak"); 
    assertEquals("From: Tallennukset line: 115", true, fbak.delete()); 
  } // Generated by ComTest END
}