package tyoSuunnittelija.test;
// Generated by ComTest BEGIN
import java.io.File;
import java.util.Iterator;
import static org.junit.Assert.*;
import org.junit.*;
import tyoSuunnittelija.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2025.04.24 10:50:17 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class TallennuksetTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa43 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa43() throws SailoException {    // Tallennukset: 43
    Tallennukset tallennukset = new Tallennukset(); 
    Tallennus testiTallennus3 = new Tallennus(), testiTallennus4 = new Tallennus(); 
    assertEquals("From: Tallennukset line: 47", 0, tallennukset.getLkm()); 
    tallennukset.lisaa(testiTallennus3); assertEquals("From: Tallennukset line: 48", 1, tallennukset.getLkm()); 
    tallennukset.lisaa(testiTallennus4); assertEquals("From: Tallennukset line: 49", 2, tallennukset.getLkm()); 
    tallennukset.lisaa(testiTallennus3); assertEquals("From: Tallennukset line: 50", 3, tallennukset.getLkm()); 
    assertEquals("From: Tallennukset line: 51", testiTallennus3, tallennukset.anna(0)); 
    assertEquals("From: Tallennukset line: 52", testiTallennus4, tallennukset.anna(1)); 
    assertEquals("From: Tallennukset line: 53", testiTallennus3, tallennukset.anna(2)); 
    assertEquals("From: Tallennukset line: 54", false, tallennukset.anna(1) == testiTallennus3); 
    assertEquals("From: Tallennukset line: 55", true, tallennukset.anna(1) == testiTallennus4); 
    tallennukset.lisaa(testiTallennus3); assertEquals("From: Tallennukset line: 56", 4, tallennukset.getLkm()); 
    tallennukset.lisaa(testiTallennus3); assertEquals("From: Tallennukset line: 57", 5, tallennukset.getLkm()); 
    tallennukset.lisaa(testiTallennus3); assertEquals("From: Tallennukset line: 58", 6, tallennukset.getLkm()); 
    tallennukset.lisaa(testiTallennus3); assertEquals("From: Tallennukset line: 59", 7, tallennukset.getLkm()); 
    tallennukset.lisaa(testiTallennus3); assertEquals("From: Tallennukset line: 60", 8, tallennukset.getLkm()); 
    tallennukset.lisaa(testiTallennus3); assertEquals("From: Tallennukset line: 61", 9, tallennukset.getLkm()); 
    tallennukset.lisaa(testiTallennus3); assertEquals("From: Tallennukset line: 62", 10, tallennukset.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testPoista98 
   * @throws SailoException when error
   */
  @Test
  public void testPoista98() throws SailoException {    // Tallennukset: 98
    Tallennukset tallennukset = new Tallennukset(); 
    Tallennus testiTal1 = new Tallennus(), testiTal2 = new Tallennus(), testiTal3 = new Tallennus(); 
    testiTal1.rekisteroi(); testiTal2.rekisteroi(); testiTal3.rekisteroi(); 
    int id1 = testiTal1.getTunnusNro(); 
    tallennukset.lisaa(testiTal1); tallennukset.lisaa(testiTal2); tallennukset.lisaa(testiTal3); 
    assertEquals("From: Tallennukset line: 105", 1, tallennukset.poista(id1+1)); 
    assertEquals("From: Tallennukset line: 106", null, tallennukset.annaId(id1+1)); assertEquals("From: Tallennukset line: 106", 2, tallennukset.getLkm()); 
    assertEquals("From: Tallennukset line: 107", 1, tallennukset.poista(id1)); assertEquals("From: Tallennukset line: 107", 1, tallennukset.getLkm()); 
    assertEquals("From: Tallennukset line: 108", 0, tallennukset.poista(id1+3)); assertEquals("From: Tallennukset line: 108", 1, tallennukset.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testAnnaId128 
   * @throws SailoException when error
   */
  @Test
  public void testAnnaId128() throws SailoException {    // Tallennukset: 128
    Tallennukset tallennukset = new Tallennukset(); 
    Tallennus testiTal1 = new Tallennus(), testiTal2 = new Tallennus(), testiTal3 = new Tallennus(); 
    testiTal1.rekisteroi(); testiTal2.rekisteroi(); testiTal3.rekisteroi(); 
    int id1 = testiTal1.getTunnusNro(); 
    tallennukset.lisaa(testiTal1); tallennukset.lisaa(testiTal2); tallennukset.lisaa(testiTal3); 
    assertEquals("From: Tallennukset line: 135", true, tallennukset.annaId(id1  ) == testiTal1); 
    assertEquals("From: Tallennukset line: 136", true, tallennukset.annaId(id1+1) == testiTal2); 
    assertEquals("From: Tallennukset line: 137", true, tallennukset.annaId(id1+2) == testiTal3); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testEtsiId152 
   * @throws SailoException when error
   */
  @Test
  public void testEtsiId152() throws SailoException {    // Tallennukset: 152
    Tallennukset Tallennukset = new Tallennukset(); 
    Tallennus testiTal1 = new Tallennus(), testiTal2 = new Tallennus(), testiTal3 = new Tallennus(); 
    testiTal1.rekisteroi(); testiTal2.rekisteroi(); testiTal3.rekisteroi(); 
    int id1 = testiTal1.getTunnusNro(); 
    Tallennukset.lisaa(testiTal1); Tallennukset.lisaa(testiTal2); Tallennukset.lisaa(testiTal3); 
    assertEquals("From: Tallennukset line: 159", 1, Tallennukset.etsiId(id1+1)); 
    assertEquals("From: Tallennukset line: 160", 2, Tallennukset.etsiId(id1+2)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta190 
   * @throws SailoException when error
   */
  @Test
  public void testLueTiedostosta190() throws SailoException {    // Tallennukset: 190
    Tallennukset tallennukset = new Tallennukset(); 
    Tallennus tallennus1 = new Tallennus(), tallennus2 = new Tallennus(); 
    tallennus1.kokeileTallennus(); 
    tallennus2.kokeileTallennus(); 
    String tiedNimi = "data\\testidata\\testiTallennukset"; 
    File ftied = new File(tiedNimi+".dat"); 
    try {
    tallennukset.lueTiedostosta(ftied.getName()); 
    fail("Tallennukset: 202 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    tallennukset.lisaa(tallennus1); 
    tallennukset.lisaa(tallennus2); 
    tallennukset.talleta(); 
    tallennukset.lueTiedostosta(tiedNimi+".dat"); 
    Iterator<Tallennus> i = tallennukset.iterator(); 
    assertEquals("From: Tallennukset line: 209", tallennus1, i.next()); 
    assertEquals("From: Tallennukset line: 210", tallennus2, i.next()); 
    assertEquals("From: Tallennukset line: 211", false, i.hasNext()); 
    tallennukset.lisaa(tallennus2); 
    tallennukset.talleta(); 
    assertEquals("From: Tallennukset line: 214", true, ftied.delete()); 
  } // Generated by ComTest END
}