package tyoSuunnittelija.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import tyoSuunnittelija.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2025.03.16 16:40:24 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class TallennusTest {



  // Generated by ComTest BEGIN
  /** testGetNimi23 */
  @Test
  public void testGetNimi23() {    // Tallennus: 23
    Tallennus testiTallennus2 = new Tallennus(); 
    testiTallennus2.kokeileTallennus(); 
    { String _l_=testiTallennus2.getNimi(),_r_="Tallennus .*"; if ( !_l_.matches(_r_) ) fail("From: Tallennus line: 26" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}; 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi67 */
  @Test
  public void testRekisteroi67() {    // Tallennus: 67
    Tallennus testiTallennus2 = new Tallennus(); 
    assertEquals("From: Tallennus line: 69", 0, testiTallennus2.getTunnusNro()); 
    testiTallennus2.rekisteroi(); 
    Tallennus testiTallennus3 = new Tallennus(); 
    testiTallennus3.rekisteroi(); 
    int n1 = testiTallennus2.getTunnusNro(); 
    int n2 = testiTallennus3.getTunnusNro(); 
    assertEquals("From: Tallennus line: 75", n2-1, n1); 
  } // Generated by ComTest END
}