package tyoSuunnittelija.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import tyoSuunnittelija.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2025.03.16 17:03:23 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class TallennuksetTest {


  // Generated by ComTest BEGIN
  /** 
   * testLisaa27 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa27() throws SailoException {    // Tallennukset: 27
    Tallennukset tallennukset = new Tallennukset(); 
    Tallennus testiTallennus3 = new Tallennus(), testiTallennus4 = new Tallennus(); 
    assertEquals("From: Tallennukset line: 31", 0, tallennukset.getLkm()); 
    tallennukset.lisaa(testiTallennus3); assertEquals("From: Tallennukset line: 32", 1, tallennukset.getLkm()); 
    tallennukset.lisaa(testiTallennus4); assertEquals("From: Tallennukset line: 33", 2, tallennukset.getLkm()); 
    tallennukset.lisaa(testiTallennus3); assertEquals("From: Tallennukset line: 34", 3, tallennukset.getLkm()); 
    assertEquals("From: Tallennukset line: 35", testiTallennus3, tallennukset.anna(0)); 
    assertEquals("From: Tallennukset line: 36", testiTallennus4, tallennukset.anna(1)); 
    assertEquals("From: Tallennukset line: 37", testiTallennus3, tallennukset.anna(2)); 
    assertEquals("From: Tallennukset line: 38", false, tallennukset.anna(1) == testiTallennus3); 
    assertEquals("From: Tallennukset line: 39", true, tallennukset.anna(1) == testiTallennus4); 
    try {
    assertEquals("From: Tallennukset line: 40", testiTallennus3, tallennukset.anna(3)); 
    fail("Tallennukset: 40 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    tallennukset.lisaa(testiTallennus3); assertEquals("From: Tallennukset line: 41", 4, tallennukset.getLkm()); 
    tallennukset.lisaa(testiTallennus3); assertEquals("From: Tallennukset line: 42", 5, tallennukset.getLkm()); 
    tallennukset.lisaa(testiTallennus3); assertEquals("From: Tallennukset line: 43", 6, tallennukset.getLkm()); 
    tallennukset.lisaa(testiTallennus3); assertEquals("From: Tallennukset line: 44", 7, tallennukset.getLkm()); 
    tallennukset.lisaa(testiTallennus3); assertEquals("From: Tallennukset line: 45", 8, tallennukset.getLkm()); 
    tallennukset.lisaa(testiTallennus3); assertEquals("From: Tallennukset line: 46", 9, tallennukset.getLkm()); 
    tallennukset.lisaa(testiTallennus3); assertEquals("From: Tallennukset line: 47", 10, tallennukset.getLkm()); 
    try {
    tallennukset.lisaa(testiTallennus3); 
    fail("Tallennukset: 48 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END
}