package tyoSuunnittelija.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import tyoSuunnittelija.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2025.03.16 17:27:58 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class TyoSuunnittelijaTest {


  // Generated by ComTest BEGIN
  /** 
   * testLisaa38 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa38() throws SailoException {    // TyoSuunnittelija: 38
    TyoSuunnittelija tyoSuunnittelija = new TyoSuunnittelija(); 
    Tallennus testiTallennus3 = new Tallennus(), testiTallennus4 = new Tallennus(); 
    testiTallennus3.rekisteroi(); testiTallennus4.rekisteroi(); 
    assertEquals("From: TyoSuunnittelija line: 43", 0, tyoSuunnittelija.getTallennuksia()); 
    tyoSuunnittelija.lisaa(testiTallennus3); assertEquals("From: TyoSuunnittelija line: 44", 1, tyoSuunnittelija.getTallennuksia()); 
    tyoSuunnittelija.lisaa(testiTallennus4); assertEquals("From: TyoSuunnittelija line: 45", 2, tyoSuunnittelija.getTallennuksia()); 
    tyoSuunnittelija.lisaa(testiTallennus3); assertEquals("From: TyoSuunnittelija line: 46", 3, tyoSuunnittelija.getTallennuksia()); 
    assertEquals("From: TyoSuunnittelija line: 47", testiTallennus3, tyoSuunnittelija.annaTallennukset(0)); 
    assertEquals("From: TyoSuunnittelija line: 48", testiTallennus4, tyoSuunnittelija.annaTallennukset(1)); 
    assertEquals("From: TyoSuunnittelija line: 49", testiTallennus3, tyoSuunnittelija.annaTallennukset(2)); 
    assertEquals("From: TyoSuunnittelija line: 50", false, tyoSuunnittelija.annaTallennukset(1) == testiTallennus3); 
    assertEquals("From: TyoSuunnittelija line: 51", true, tyoSuunnittelija.annaTallennukset(1) == testiTallennus4); 
    try {
    assertEquals("From: TyoSuunnittelija line: 52", testiTallennus3, tyoSuunnittelija.annaTallennukset(3)); 
    fail("TyoSuunnittelija: 52 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    tyoSuunnittelija.lisaa(testiTallennus3); assertEquals("From: TyoSuunnittelija line: 53", 4, tyoSuunnittelija.getTallennuksia()); 
    tyoSuunnittelija.lisaa(testiTallennus3); assertEquals("From: TyoSuunnittelija line: 54", 5, tyoSuunnittelija.getTallennuksia()); 
    tyoSuunnittelija.lisaa(testiTallennus3); assertEquals("From: TyoSuunnittelija line: 55", 6, tyoSuunnittelija.getTallennuksia()); 
    tyoSuunnittelija.lisaa(testiTallennus3); assertEquals("From: TyoSuunnittelija line: 56", 7, tyoSuunnittelija.getTallennuksia()); 
    tyoSuunnittelija.lisaa(testiTallennus3); assertEquals("From: TyoSuunnittelija line: 57", 8, tyoSuunnittelija.getTallennuksia()); 
    tyoSuunnittelija.lisaa(testiTallennus3); assertEquals("From: TyoSuunnittelija line: 58", 9, tyoSuunnittelija.getTallennuksia()); 
    tyoSuunnittelija.lisaa(testiTallennus3); assertEquals("From: TyoSuunnittelija line: 59", 10, tyoSuunnittelija.getTallennuksia()); 
    try {
    tyoSuunnittelija.lisaa(testiTallennus3); 
    fail("TyoSuunnittelija: 60 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END
}