package tyoSuunnittelija.test;
// Generated by ComTest BEGIN
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
import tyoSuunnittelija.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2025.03.17 18:46:20 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class TyoSuunnittelijaTest {



  // Generated by ComTest BEGIN
  /** testAnnaPellot30 */
  @Test
  public void testAnnaPellot30() {    // TyoSuunnittelija: 30
    TyoSuunnittelija tyoSuunnittelija = new TyoSuunnittelija(); 
    Tallennus testiTallennus3 = new Tallennus(), testiTallennus4 = new Tallennus(), testiTallennus5 = new Tallennus(); 
    testiTallennus3.rekisteroi(); testiTallennus4.rekisteroi(); testiTallennus5.rekisteroi(); 
    int id1 = testiTallennus3.getTunnusNro(); 
    int id2 = testiTallennus4.getTunnusNro(); 
    Pelto testiPelto11 = new Pelto(id1); tyoSuunnittelija.lisaa(testiPelto11); 
    Pelto testiPelto12 = new Pelto(id1); tyoSuunnittelija.lisaa(testiPelto12); 
    Pelto testiPelto21 = new Pelto(id2); tyoSuunnittelija.lisaa(testiPelto21); 
    Pelto testiPelto22 = new Pelto(id2); tyoSuunnittelija.lisaa(testiPelto22); 
    Pelto testiPelto23 = new Pelto(id2); tyoSuunnittelija.lisaa(testiPelto23); 
    List<Pelto> loytyneet; 
    loytyneet = tyoSuunnittelija.annaPellot(testiTallennus5); 
    assertEquals("From: TyoSuunnittelija line: 46", 0, loytyneet.size()); 
    loytyneet = tyoSuunnittelija.annaPellot(testiTallennus3); 
    assertEquals("From: TyoSuunnittelija line: 48", 2, loytyneet.size()); 
    assertEquals("From: TyoSuunnittelija line: 49", true, loytyneet.get(0) == testiPelto11); 
    assertEquals("From: TyoSuunnittelija line: 50", true, loytyneet.get(1) == testiPelto12); 
    loytyneet = tyoSuunnittelija.annaPellot(testiTallennus4); 
    assertEquals("From: TyoSuunnittelija line: 52", 3, loytyneet.size()); 
    assertEquals("From: TyoSuunnittelija line: 53", true, loytyneet.get(0) == testiPelto21); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLisaa87 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa87() throws SailoException {    // TyoSuunnittelija: 87
    TyoSuunnittelija tyoSuunnittelija = new TyoSuunnittelija(); 
    Tallennus testiTallennus3 = new Tallennus(), testiTallennus4 = new Tallennus(); 
    testiTallennus3.rekisteroi(); testiTallennus4.rekisteroi(); 
    assertEquals("From: TyoSuunnittelija line: 92", 0, tyoSuunnittelija.getTallennuksia()); 
    tyoSuunnittelija.lisaa(testiTallennus3); assertEquals("From: TyoSuunnittelija line: 93", 1, tyoSuunnittelija.getTallennuksia()); 
    tyoSuunnittelija.lisaa(testiTallennus4); assertEquals("From: TyoSuunnittelija line: 94", 2, tyoSuunnittelija.getTallennuksia()); 
    tyoSuunnittelija.lisaa(testiTallennus3); assertEquals("From: TyoSuunnittelija line: 95", 3, tyoSuunnittelija.getTallennuksia()); 
    assertEquals("From: TyoSuunnittelija line: 96", testiTallennus3, tyoSuunnittelija.annaTallennukset(0)); 
    assertEquals("From: TyoSuunnittelija line: 97", testiTallennus4, tyoSuunnittelija.annaTallennukset(1)); 
    assertEquals("From: TyoSuunnittelija line: 98", testiTallennus3, tyoSuunnittelija.annaTallennukset(2)); 
    assertEquals("From: TyoSuunnittelija line: 99", false, tyoSuunnittelija.annaTallennukset(1) == testiTallennus3); 
    assertEquals("From: TyoSuunnittelija line: 100", true, tyoSuunnittelija.annaTallennukset(1) == testiTallennus4); 
    try {
    assertEquals("From: TyoSuunnittelija line: 101", testiTallennus3, tyoSuunnittelija.annaTallennukset(3)); 
    fail("TyoSuunnittelija: 101 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    tyoSuunnittelija.lisaa(testiTallennus3); assertEquals("From: TyoSuunnittelija line: 102", 4, tyoSuunnittelija.getTallennuksia()); 
    tyoSuunnittelija.lisaa(testiTallennus3); assertEquals("From: TyoSuunnittelija line: 103", 5, tyoSuunnittelija.getTallennuksia()); 
    tyoSuunnittelija.lisaa(testiTallennus3); assertEquals("From: TyoSuunnittelija line: 104", 6, tyoSuunnittelija.getTallennuksia()); 
    tyoSuunnittelija.lisaa(testiTallennus3); assertEquals("From: TyoSuunnittelija line: 105", 7, tyoSuunnittelija.getTallennuksia()); 
    tyoSuunnittelija.lisaa(testiTallennus3); assertEquals("From: TyoSuunnittelija line: 106", 8, tyoSuunnittelija.getTallennuksia()); 
    tyoSuunnittelija.lisaa(testiTallennus3); assertEquals("From: TyoSuunnittelija line: 107", 9, tyoSuunnittelija.getTallennuksia()); 
    tyoSuunnittelija.lisaa(testiTallennus3); assertEquals("From: TyoSuunnittelija line: 108", 10, tyoSuunnittelija.getTallennuksia()); 
    try {
    tyoSuunnittelija.lisaa(testiTallennus3); 
    fail("TyoSuunnittelija: 109 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END
}