package tyoSuunnittelija.test;
// Generated by ComTest BEGIN
import tyoSuunnittelija.SailoException;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
import tyoSuunnittelija.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2025.04.24 10:50:31 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class TyoSuunnittelijaTest {


  // Generated by ComTest BEGIN  // TyoSuunnittelija: 15
   private TyoSuunnittelija tyoSuunnittelija; 
   private Tallennus testiTal1; 
   private Tallennus testiTal2; 
   private int tid1; 
   private int tid2; 
   private Pelto testiPelto21; 
   private Pelto testiPelto11; 
   private Pelto testiPelto22; 
   private Pelto testiPelto12; 
   private Pelto testiPelto23; 

   public void alustaTyoSuunnittelija() {
     tyoSuunnittelija = new TyoSuunnittelija(); 
     testiTal1 = new Tallennus(); testiTal1.kokeileTallennus(); testiTal1.rekisteroi(); 
     testiTal2 = new Tallennus(); testiTal2.kokeileTallennus(); testiTal2.rekisteroi(); 
     tid1 = testiTal1.getTunnusNro(); 
     tid2 = testiTal2.getTunnusNro(); 
     testiPelto21 = new Pelto(tid2); testiPelto21.kokeilePelto(tid2); 
     testiPelto11 = new Pelto(tid1); testiPelto11.kokeilePelto(tid1); 
     testiPelto22 = new Pelto(tid2); testiPelto22.kokeilePelto(tid2); 
     testiPelto12 = new Pelto(tid1); testiPelto12.kokeilePelto(tid1); 
     testiPelto23 = new Pelto(tid2); testiPelto23.kokeilePelto(tid2); 
     try {
     tyoSuunnittelija.lisaa(testiTal1); 
     tyoSuunnittelija.lisaa(testiTal2); 
     tyoSuunnittelija.lisaa(testiPelto21); 
     tyoSuunnittelija.lisaa(testiPelto11); 
     tyoSuunnittelija.lisaa(testiPelto22); 
     tyoSuunnittelija.lisaa(testiPelto12); 
     tyoSuunnittelija.lisaa(testiPelto23); 
     } catch ( Exception e) {
        System.err.println(e.getMessage()); 
     }
   }
  // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaPellot96 */
  @Test
  public void testAnnaPellot96() {    // TyoSuunnittelija: 96
    alustaTyoSuunnittelija(); 
    TyoSuunnittelija tyoSuunnittelija = new TyoSuunnittelija(); 
    Tallennus testiTallennus3 = new Tallennus(), testiTallennus4 = new Tallennus(), testiTallennus5 = new Tallennus(); 
    testiTallennus3.rekisteroi(); testiTallennus4.rekisteroi(); testiTallennus5.rekisteroi(); 
    int id1 = testiTallennus3.getTunnusNro(); 
    int id2 = testiTallennus4.getTunnusNro(); 
    Pelto testiPelto11 = new Pelto(id1); tyoSuunnittelija.lisaa(testiPelto11); 
    Pelto testiPelto12 = new Pelto(id1); tyoSuunnittelija.lisaa(testiPelto12); 
    Pelto testiPelto21 = new Pelto(id2); tyoSuunnittelija.lisaa(testiPelto21); 
    Pelto testiPelto22 = new Pelto(id2); tyoSuunnittelija.lisaa(testiPelto22); 
    Pelto testiPelto23 = new Pelto(id2); tyoSuunnittelija.lisaa(testiPelto23); 
    List<Pelto> loytyneet; 
    loytyneet = tyoSuunnittelija.annaPellot(testiTallennus5); 
    assertEquals("From: TyoSuunnittelija line: 112", 0, loytyneet.size()); 
    loytyneet = tyoSuunnittelija.annaPellot(testiTallennus3); 
    assertEquals("From: TyoSuunnittelija line: 114", 2, loytyneet.size()); 
    assertEquals("From: TyoSuunnittelija line: 115", true, loytyneet.get(0) == testiPelto11); 
    assertEquals("From: TyoSuunnittelija line: 116", true, loytyneet.get(1) == testiPelto12); 
    loytyneet = tyoSuunnittelija.annaPellot(testiTallennus4); 
    assertEquals("From: TyoSuunnittelija line: 118", 3, loytyneet.size()); 
    assertEquals("From: TyoSuunnittelija line: 119", true, loytyneet.get(0) == testiPelto21); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testPoistaPel163 
   * @throws Exception when error
   */
  @Test
  public void testPoistaPel163() throws Exception {    // TyoSuunnittelija: 163
    alustaTyoSuunnittelija(); 
    assertEquals("From: TyoSuunnittelija line: 166", 2, tyoSuunnittelija.annaPellot(testiTal1).size()); 
    tyoSuunnittelija.poistaPel(testiPelto11); 
    assertEquals("From: TyoSuunnittelija line: 168", 1, tyoSuunnittelija.annaPellot(testiTal1).size()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLisaa180 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa180() throws SailoException {    // TyoSuunnittelija: 180
    alustaTyoSuunnittelija(); 
    TyoSuunnittelija tyoSuunnittelija = new TyoSuunnittelija(); 
    Tallennus testiTallennus3 = new Tallennus(), testiTallennus4 = new Tallennus(); 
    testiTallennus3.rekisteroi(); testiTallennus4.rekisteroi(); 
    assertEquals("From: TyoSuunnittelija line: 186", 0, tyoSuunnittelija.getTallennuksia()); 
    tyoSuunnittelija.lisaa(testiTallennus3); assertEquals("From: TyoSuunnittelija line: 187", 1, tyoSuunnittelija.getTallennuksia()); 
    tyoSuunnittelija.lisaa(testiTallennus4); assertEquals("From: TyoSuunnittelija line: 188", 2, tyoSuunnittelija.getTallennuksia()); 
    tyoSuunnittelija.lisaa(testiTallennus3); assertEquals("From: TyoSuunnittelija line: 189", 3, tyoSuunnittelija.getTallennuksia()); 
    assertEquals("From: TyoSuunnittelija line: 190", testiTallennus3, tyoSuunnittelija.annaTallennukset(0)); 
    assertEquals("From: TyoSuunnittelija line: 191", testiTallennus4, tyoSuunnittelija.annaTallennukset(1)); 
    assertEquals("From: TyoSuunnittelija line: 192", testiTallennus3, tyoSuunnittelija.annaTallennukset(2)); 
    assertEquals("From: TyoSuunnittelija line: 193", false, tyoSuunnittelija.annaTallennukset(1) == testiTallennus3); 
    assertEquals("From: TyoSuunnittelija line: 194", true, tyoSuunnittelija.annaTallennukset(1) == testiTallennus4); 
    try {
    assertEquals("From: TyoSuunnittelija line: 195", testiTallennus3, tyoSuunnittelija.annaTallennukset(3)); 
    fail("TyoSuunnittelija: 195 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    tyoSuunnittelija.lisaa(testiTallennus3); assertEquals("From: TyoSuunnittelija line: 196", 4, tyoSuunnittelija.getTallennuksia()); 
    tyoSuunnittelija.lisaa(testiTallennus3); assertEquals("From: TyoSuunnittelija line: 197", 5, tyoSuunnittelija.getTallennuksia()); 
    tyoSuunnittelija.lisaa(testiTallennus3); assertEquals("From: TyoSuunnittelija line: 198", 6, tyoSuunnittelija.getTallennuksia()); 
    tyoSuunnittelija.lisaa(testiTallennus3); assertEquals("From: TyoSuunnittelija line: 199", 7, tyoSuunnittelija.getTallennuksia()); 
    tyoSuunnittelija.lisaa(testiTallennus3); assertEquals("From: TyoSuunnittelija line: 200", 8, tyoSuunnittelija.getTallennuksia()); 
    tyoSuunnittelija.lisaa(testiTallennus3); assertEquals("From: TyoSuunnittelija line: 201", 9, tyoSuunnittelija.getTallennuksia()); 
    tyoSuunnittelija.lisaa(testiTallennus3); assertEquals("From: TyoSuunnittelija line: 202", 10, tyoSuunnittelija.getTallennuksia()); 
  } // Generated by ComTest END
}